#!/usr/bin/env bash
#
# A wizard walks a human through setting up staging Supabase secrets for GitHub Actions E2E tests.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=4
_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env.staging}"
WRITTEN_ENV=()
WRITTEN_SECRET=()
SKIPPED=()

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  This wizard sets up your dedicated Supabase STAGING credentials\n' "$DIM"
  printf '  for GitHub Actions E2E testing without ever touching production data.\n'
  printf '  It captures the keys and stores them as GitHub repository secrets via `gh`.%s\n\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview      >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open     >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open         >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

ask() {
  local key="$1" prompt="$2" input=""
  printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  read -r input || true
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" input=""
  printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  read -rs input || true
  printf '\n'
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set manually: gh secret set $name)")
  warn "gh cli couldn't write secret $name automatically. Add it manually in GitHub Settings."
}

finish() {
  _clear
  printf '\n%s%s  ✓ Staging Secrets Setup Complete%s\n\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_SECRET[@]} )) && note "Set ${#WRITTEN_SECRET[@]} secret(s) in GitHub Actions: ${WRITTEN_SECRET[*]}"
  (( ${#WRITTEN_ENV[@]} ))    && note "Saved local staging reference in: $ENV_FILE"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "Still to set manually in GitHub (repo → Settings → Secrets → Actions):"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
  printf '  %sNext steps:%s\n' "$BOLD" "$RESET"
  printf '  1. Re-run the failed GitHub Actions E2E job (Actions tab → Re-run all jobs)\n'
  printf '  2. Confirm `auth.setup.ts` and journeys run green against staging!\n\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Staging Supabase Credentials & GitHub Secrets
# ──────────────────────────────────────────────────────────────────────────

banner "Staging Supabase CI Secrets Setup"

# ── Stage 1: Confirm Staging Project ───────────────────────────────────────
stage "Supabase: Staging Project Verification"
say "We must verify your separate Staging project exists on Supabase."
say "E2E tests will create and purge test users, contracts, and documents."
warn "NEVER point CI at your production database!"
step "Open your Supabase dashboard to verify or create your Staging project."
open_url "https://supabase.com/dashboard/projects"
say ""
step "Ensure migrations are applied to your staging database:"
note "   supabase db push (or execute supabase/migrations/*.sql in SQL Editor)"
pause "Press Enter once your staging project is created and ready"

# ── Stage 2: Project URL ──────────────────────────────────────────────────
stage "Capture: NEXT_PUBLIC_SUPABASE_URL"
say "Navigate to your STAGING project settings:"
step "In Supabase, select your Staging project → Project Settings → API"
open_url "https://supabase.com/dashboard/project/_/settings/api"
step "Copy the 'Project URL' (format: https://<project-ref>.supabase.co)"
ask STAGING_SUPABASE_URL "Paste staging Project URL:"

if [[ -n "$STAGING_SUPABASE_URL" ]]; then
  write_env NEXT_PUBLIC_SUPABASE_URL "$STAGING_SUPABASE_URL"
  set_secret NEXT_PUBLIC_SUPABASE_URL "$STAGING_SUPABASE_URL"
fi

# ── Stage 3: Anon Public Key ──────────────────────────────────────────────
stage "Capture: NEXT_PUBLIC_SUPABASE_ANON_KEY"
say "On the same API settings page:"
step "Copy the 'Project API keys' → 'anon' (public) key."
ask STAGING_SUPABASE_ANON "Paste staging anon public key:"

if [[ -n "$STAGING_SUPABASE_ANON" ]]; then
  write_env NEXT_PUBLIC_SUPABASE_ANON_KEY "$STAGING_SUPABASE_ANON"
  set_secret NEXT_PUBLIC_SUPABASE_ANON_KEY "$STAGING_SUPABASE_ANON"
fi

# ── Stage 4: Service Role Secret Key ──────────────────────────────────────
stage "Capture: SUPABASE_SERVICE_ROLE_KEY"
say "On the same API settings page:"
warn "This is your admin service_role secret. It bypasses RLS for test setup and teardown."
step "Click 'Reveal' next to 'service_role' (secret) key and copy it."
ask_secret STAGING_SUPABASE_SERVICE_KEY "Paste staging service_role key (hidden):"

if [[ -n "$STAGING_SUPABASE_SERVICE_KEY" ]]; then
  write_env SUPABASE_SERVICE_ROLE_KEY "$STAGING_SUPABASE_SERVICE_KEY"
  set_secret SUPABASE_SERVICE_ROLE_KEY "$STAGING_SUPABASE_SERVICE_KEY"
fi

finish
